shopping-list-assistant/config/routes.rb
Rails.application.routes.draw do
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :lists
end

shopping-list-assistant/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

shopping-list-assistant/app/models/list.rb
class List < ApplicationRecord
end

shopping-list-assistant/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

shopping-list-assistant/app/controllers/home_controller.rb
#
# Home controller
#
class HomeController < ApplicationController
  def index; end
end

shopping-list-assistant/app/controllers/lists_controller.rb
#
# List controller
#
class ListsController < ApplicationController
  before_action :find_list, only: %i[edit show update]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def edit; end

  def show; end

  # API Actions

  def create
    @list = List.create(name: params[:list][:name], archived: false, total_items: 0)

    redirect_to @list
  end

  def update
    @list.update(name: params[:list][:name])
    redirect_to @list
  end

  def destroy
    List.destroy_by(id: params[:id])
    redirect_to action: 'index'
  end

  def find_list
    @list = List.find(params[:id])
  end
end

shopping-list-assistant/app/helpers/application_helper.rb
module ApplicationHelper
end

shopping-list-assistant/app/helpers/home_helper.rb
module HomeHelper
end

shopping-list-assistant/app/helpers/lists_helper.rb
module ListsHelper
end

shopping-list-assistant/app/views/home/index.html.erb
<h1>Shopping list assistant</h1>

<p>here you can find a shopping your assistant</p>

shopping-list-assistant/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingListAssistant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav'%>
    <%= yield %>
  </body>
</html>

shopping-list-assistant/app/views/lists/_form.html.erb
<%= form_with(model: @list, local: true) do | form | %>
  <div class='field'>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<%end%>

shopping-list-assistant/app/views/lists/_list.html.erb
<div class='card padding margin-top'>
  <div class='row'>
    <div class='col-8 text-uppercase'>
      <h3><%= list.name %></h3>
    </div>
    <div class='col-4'>
      <div class='btn btn-link'>
        <%= link_to 'Details', list %>
      </div>
      <div class='btn btn-link'>
        <%= link_to 'Edit', list %>
      </div>
      <div class='btn btn-link'>
        <%= link_to 'Remove', list %>
      </div>
    </div>
  </div>
  <p >Items: <%= list.total_items %></p>
  <p class='text-secondary'>Created at: <%= list.created_at %></p>
</div>

shopping-list-assistant/app/views/lists/edit.html.erb
<div class='small-container center-block'>
  <%= render 'lists/form' %>
</div>

shopping-list-assistant/app/views/lists/index.html.erb
<div class='large-container center-block'>
  <h1>My Shopping Lists</h1>
  <div class='row'>
    <%= link_to 'Add list', new_list_url, class: 'col offset-md-9 btn btn-light' %>
  </div>
  <%= render @lists %>
</div>

shopping-list-assistant/app/views/lists/new.html.erb
<br />

<%= form_with(model: @list) do | form | %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<%end%>

shopping-list-assistant/app/views/lists/show.html.erb
<div class='small-container center-block padding'>
  <div>
    <h3 class='text-uppercase'><%= @list.name %></h3>
  </div>
  <div>
    <p>Items: <%= @list.total_items %></p>
    <div class='row'>
      <p class='col-6 text-secondary'>Created at: <%= @list.created_at %></p>
      <p class='col-6 text-secondary'>Updated at: <%= @list.updated_at %></p>
    </div>
  </div>
  <div>
    <%= link_to 'Remove', @list, method: :delete %>
    <%= link_to 'Edit', edit_list_url %>
  </div>
</div>

shopping-list-assistant/app/views/partials/_nav.html.erb
<nav class='nav bg-light padding'>
  <li class='nav-item'>
    <%= link_to 'Home', root_path, class: 'nav-link'%>
  </li>
  <li class='nav-item'>
    <%= link_to 'My Lists', lists_url, class: 'nav-link'%>
  </li>
</nav>